/**
 * Serverless fallback snapshot accessor.
 *
 * When the live backend is unreachable, `ssrFetch` falls back to this baked
 * snapshot (generated by scripts/generate-snapshot.mjs) so the public portfolio
 * still renders the REAL content instead of empty placeholders.
 *
 * The snapshot is keyed by API path exactly as the pages request it.
 */
import snapshot from './snapshot.generated.json';

interface SnapshotFile {
  source?: string;
  partial?: boolean;
  data: Record<string, unknown>;
}

const SNAPSHOT = snapshot as SnapshotFile;

/**
 * Normalize a path so lookups are stable regardless of leading host, trailing
 * slashes, or query-parameter ordering. Keeps the pathname + sorted query.
 */
function normalizePath(path: string): string {
  let pathname = path;
  let query = '';

  // Strip an absolute origin if one was passed.
  const schemeIdx = pathname.indexOf('://');
  if (schemeIdx !== -1) {
    const afterScheme = pathname.slice(schemeIdx + 3);
    const slashIdx = afterScheme.indexOf('/');
    pathname = slashIdx === -1 ? '/' : afterScheme.slice(slashIdx);
  }

  const qIdx = pathname.indexOf('?');
  if (qIdx !== -1) {
    query = pathname.slice(qIdx + 1);
    pathname = pathname.slice(0, qIdx);
  }

  if (pathname.length > 1 && pathname.endsWith('/')) {
    pathname = pathname.slice(0, -1);
  }

  if (query) {
    const sorted = query
      .split('&')
      .filter(Boolean)
      .sort()
      .join('&');
    return `${pathname}?${sorted}`;
  }
  return pathname;
}

/**
 * Look up a baked response for the given API path.
 * Returns the response object (e.g. `{ data: ... }`) or null if not baked.
 */
export function getSnapshot<T>(path: string): T | null {
  const key = normalizePath(path);
  const direct = SNAPSHOT.data[key];
  if (direct !== undefined) return direct as T;

  // Also try the exact path as-provided (in case it was already normalized
  // by the generator differently, e.g. no sorting needed).
  const raw = SNAPSHOT.data[path];
  if (raw !== undefined) return raw as T;

  return null;
}

/** Whether any snapshot data exists at all (used for diagnostics/tests). */
export function hasSnapshotData(): boolean {
  return Object.keys(SNAPSHOT.data).length > 0;
}
